#!/usr/bin/env bash
set -e

SCREEN_OFF_TIMER=10
BLUR_TYPE="0x6"
SCREENSHOT_TEMP_PATH="${XDG_RUNTIME_DIR}/awesomeexit.png"

do_lock() {
    maim "${SCREENSHOT_TEMP_PATH}"
    convert "${SCREENSHOT_TEMP_PATH}" -blur "${BLUR_TYPE}" "${SCREENSHOT_TEMP_PATH}"
    xset s "${SCREEN_OFF_TIMER}"
    i3lock -n -u -i "${SCREENSHOT_TEMP_PATH}"
}

do_logout() {
    awesome-client "awesome.quit()" >/dev/null 2>&1 || true
}

do_reload() {
    awesome-client "awesome.restart()" >/dev/null 2>&1 || true
}

do_reboot() {
    systemctl reboot
}

do_poweroff() {
    systemctl poweroff
}

cleanup() {
    xset s 600 600
    rm "${SCREENSHOT_TEMP_PATH}" >/dev/null 2>&1 || true
}

HANDLER="${1}"
shift || true
if [[ "${HANDLER}" =~ ^(lock|logout|reload|reboot|poweroff)$ ]]; then
    trap cleanup HUP INT TERM EXIT
    "do_${HANDLER}" "$@"
else
    echo "Usage: awesomeexit <lock|logout|reload|reboot|poweroff>"
    exit 1
fi
