#!/usr/bin/env bash
set -e

LOCKSCREEN_BG="$(mktemp --tmpdir --suffix=.png awesomeexit.XXXX)"

cleanup() {
    xset s 600 600
    rm "$LOCKSCREEN_BG"
}

do_lock() {
    local blur_type
    blur_type="0x6"

    import -window root "$LOCKSCREEN_BG"
    convert "$LOCKSCREEN_BG" -blur "$blur_type" "$LOCKSCREEN_BG"
    xset s 5
    i3lock -n -u -i "$LOCKSCREEN_BG"
}

do_logout() {
    awesome-client 'awesome.quit()'
}

do_reload() {
    awesome-client 'awesome.restart()'
}

do_reboot() {
    systemctl reboot
}

do_poweroff() {
    systemctl poweroff
}

trap cleanup HUP INT TERM EXIT
case "$1" in
  lock)
    do_lock
    ;;
  logout)
    do_logout
    ;;
  reload)
    do_reload
    ;;
  reboot)
    do_reboot
    ;;
  poweroff)
    do_poweroff
    ;;
  *)
    echo "Usage: awesomeexit [lock|logout|reload|reboot|poweroff]"
    ;;
esac
